### ISSUE TITLE
Sometimes the number 'waiting-room-size' does not decrease and token(jwt) is not issued.

### ISSUE THREAD

**Issue by milestonekr** [aws-solutions/virtual-waiting-room-on-aws#247]
I would like to inquire about two issues.

1. If you click the 'reserve' button on the waiting-room-site and close the browser on the 'check out now!' screen, the number does not decrease and remains in the 'waiting-room-size', which prevents other waiting people from entering.

2. After clicking the 'check out now!' button on the waiting-room-site, the token is often not issued when '/generate_token' is called.

How do I solve 2 issues?

**Comment by gsingh04** [comment]
Hello @milestonekr, apologies for delay in response from our end. 
1. This is because once you enter the waiting room you can still use public apis to generate token for the corresponding `request_id`. So, even though you close the browser, you are still in the waiting room and it will respond with valid jwt token if you make `POST` request for `/generate_token` with the request body
```
{
"event_id": "Sample",
"request_id": "MY_REQUEST_ID"
}
```
> See [Public REST APIs](https://github.com/aws-solutions/virtual-waiting-room-on-aws/blob/main/docs/developer-guide.md#public-rest-apis) for more details 

2. This is due to queue position expiry. Once you enter the waiting room, your position is valid for 15 minutes (by default). If you try to generate token after that, it will wail.

Please feel free to reopen the thread, if you have more questions.
